### ISSUE TITLE
Problem running example code in Jupyter; Install of ts2vg via %pip or %conda fails with same error

### ISSUE THREAD

**Issue by ondrish** [CarlosBergillos/ts2vg#26]
Hello Carlos, 

Kindly, I am trying to run the example in a freshly installed Anaconda setup on a Mac M1. 

I have created a new Jupyter Notebook, poasted the code but I keep getting this error:

```

%pip install ts2vg
from ts2vg import NaturalVG
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
ccccccccc
# 1. Generate random time series (Brownian motion)
rng = np.random.default_rng(110)
ts = rng.standard_normal(size=200)
ts = np.cumsum(ts)

# 2. Build visibility graph
g = NaturalVG(directed=None).build(ts)
nxg = g.as_networkx()

# 3. Make plots
fig, [ax0, ax1, ax2] = plt.subplots(ncols=3, figsize=(12, 3.5))

ax0.plot(ts)
ax0.set_title("Time Series")

graph_plot_options = {
    "with_labels": False,
    "node_size": 2,
    "node_color": [(0, 0, 0, 1)],
    "edge_color": [(0, 0, 0, 0.15)],
}

nx.draw_networkx(nxg, ax=ax1, pos=g.node_positions(), **graph_plot_options)
ax1.tick_params(bottom=True, labelbottom=True)
ax1.plot(ts)
ax1.set_title("Visibility Graph")

nx.draw_networkx(nxg, ax=ax2, pos=nx.kamada_kawai_layout(nxg), **graph_plot_options)
ax2.set_title("Visibility Graph")

Collecting ts2vg
  Using cached ts2vg-1.2.2.tar.gz (618 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Users/lwadmin/anaconda3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/lwadmin/anaconda3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/lwadmin/anaconda3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/9y/0tf_ch392nd_z9n63ynbj93m0000gn/T/pip-build-env-jlhi4th5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/9y/0tf_ch392nd_z9n63ynbj93m0000gn/T/pip-build-env-jlhi4th5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/9y/0tf_ch392nd_z9n63ynbj93m0000gn/T/pip-build-env-jlhi4th5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 46, in <module>
        File "<string>", line 40, in main
        File "/private/var/folders/9y/0tf_ch392nd_z9n63ynbj93m0000gn/T/pip-build-env-jlhi4th5/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 973, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/private/var/folders/9y/0tf_ch392nd_z9n63ynbj93m0000gn/T/pip-build-env-jlhi4th5/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/private/var/folders/9y/0tf_ch392nd_z9n63ynbj93m0000gn/T/pip-build-env-jlhi4th5/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'ts2vg/graph/_base.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Note: you may need to restart the kernel to use updated packages.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 2
      1 get_ipython().run_line_magic('pip', 'install ts2vg')
----> 2 from ts2vg import NaturalVG
      3 import networkx as nx
      4 import numpy as np

ModuleNotFoundError: No module named 'ts2vg'
```

**Comment by ondrish** [comment]
may this be related to ts2vg not supporting python 3.10? that is being installed with Anaconda currently.
<img width="786" alt="MicrosoftTeams-image (1)" src="https://github.com/CarlosBergillos/ts2vg/assets/967450/7842c7c9-7176-472c-b050-8c645f16071f">

**Comment by CarlosBergillos** [comment]
Hey, thanks for the report.

There is currently two problems:
- Building the package from source is not working. Only installing from pre-built wheels is supported. (fixing this is on my todo list but haven't had time to work on it),
- In particular, I am explicitly not building wheels for Python 3.10 on MacOs on purpose. Due to a bug outside of my control (same as: https://github.com/pypa/cibuildwheel/issues/402).

With that said, maybe that bug was solved, I don't know, I'll try building it again and I'll let you know.

Sorr for the inconvenience.

**Comment by CarlosBergillos** [comment]
Seems it all built fine. Can you try installing ts2vg again?
