### ISSUE TITLE
Installation fails for python 3.11 environment 

### ISSUE THREAD

**Issue by jjruby09** [CarlosBergillos/ts2vg#9]
I am trying to install using `pip install ts2vg` within an anaconda environment and the install fails when trying to build the wheel, output: 

```
Collecting ts2vg
  Using cached ts2vg-1.1.1.tar.gz (392 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "C:\Users\jruby\Anaconda3\envs\ts_graph\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\jruby\Anaconda3\envs\ts_graph\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jruby\Anaconda3\envs\ts_graph\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jruby\AppData\Local\Temp\pip-build-env-y5h9bj_v\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jruby\AppData\Local\Temp\pip-build-env-y5h9bj_v\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\jruby\AppData\Local\Temp\pip-build-env-y5h9bj_v\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 36, in <module>
        File "<string>", line 31, in main
        File "C:\Users\jruby\AppData\Local\Temp\pip-build-env-y5h9bj_v\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jruby\AppData\Local\Temp\pip-build-env-y5h9bj_v\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "C:\Users\jruby\AppData\Local\Temp\pip-build-env-y5h9bj_v\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'ts2vg/utils/pairqueue.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I have been able to reproduce this issue on both a windows 10 machine and an Ubuntu VM both with fresh environments. I have successfully installed in python 3.10 envs.

**Comment by CarlosBergillos** [comment]
Oh, seems the pre-built 3.11 wheels are missing from the release for some reason (and pip is failing at compiling it from source).

I'll take a look at it this weekend and see if I can generate and upload the 3.11 wheels. Hopefully it's a very quick fix.

Thanks a lot for the report!

**Comment by CarlosBergillos** [comment]
I fixed the build script and included the missing wheels.
Installation in Python 3.11 should now work.
